apiVersion: v1
kind: Namespace
metadata:
  name: wipcontrol
---

apiVersion: v1
kind: Service
metadata:
  name: wipcontrol-front
  namespace: wipcontrol
spec:
  selector:
    app: wipcontrol-front
  ports:
  - protocol: "TCP"
    port: 5768
    targetPort: 5768
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wipcontrol-front
  namespace: wipcontrol
spec:
  selector:
    matchLabels:
      app: wipcontrol-front
  replicas: 1
  template:
    metadata:
      labels:
        app: wipcontrol-front
    spec:
      containers:
      - name: wipcontrol-front
        image: wipcontrolacr.azurecr.io/wipcontrol-front:v1
        ports:
        - containerPort: 5678
        command: ["npm", "run", "dev"]
---