apiVersion: v1
kind: Namespace
metadata:
  name: wipcontrol

---

apiVersion: v1
kind: Service
metadata:
  name: wipcontrol-mysql
  namespace: wipcontrol
spec:
  selector:
    app: wipcontrol-mysql
  ports:
  - protocol: "TCP"
    port: 5768
    targetPort: 5768
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wipcontrol-mysql
  namespace: wipcontrol
spec:
  selector:
    matchLabels:
      app: wipcontrol-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: wipcontrol-mysql
    spec:
      containers:
      - name: wipcontrol-mysql
        image: wipcontrolacr.azurecr.io/wipcontrol-mysql:v1
        ports:
        - containerPort: 5678
---