name: "Deploy Backend"
on:
  workflow_dispatch:
  push:
    paths:
      - "k8s-manifest/backend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      
      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login wipcontrolacr.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
         
      - name: Build and push Docker image
        run: |
            docker build -t wipcontrolacr.azurecr.io/wipcontrol-back:v1 -f backend/Dockerfile2 .
            docker push wipcontrolacr.azurecr.io/wipcontrol-back:v1
 
      - name: Logout from Azure Container Registry
        run: docker logout wipcontrolacr.azurecr.io

      - name: Set up Azure CLI
        uses: azure/cli@v1
        with:
          inlineScript: az --version

      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION }}
      
      - name: Get AKS credentials
        run: az aks get-credentials --resource-group wipcontrol-rg --name wipcontrolaks
    
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment/k8s-manifest/backend/deploy-back.yaml
          kubectl set image deployment/wipcontrol-back wipcontrol-back=wipcontrolacr.azurecr.io/wipcontrol-backend:v1
          kubectl rollout status deployment/wipcontrol-back