name: "Deploy MySql"
on:
  workflow_dispatch:
  push:
    paths:
      - "k8s-manifest/mysql/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      # - name: ACR build
      #   id: build-push-acr
      #   uses: azure/acr-build@v1
      #   with:
      #     service_principal: ${{ secrets.AZURE_CLIENT_ID }}
      #     service_principal_password: ${{ secrets.AZURE_CLIENT_SECRET }}
      #     tenant: ${{ secrets.AZURE_TENANT_ID }}
      #     registry: wipcontrolacr
      #     repository: wipcontrolacr
      #     image:  wipcontrol-mysql
      #     # folder: wipcontrol
      #     branch: master
      #     tag: v1
      # - name: 'Docker Login'
      #   uses: azure/docker-login@v1
      #   with:
      #    login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      #    username: ${{ secrets.REGISTRY_USERNAME }}
      #    password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login wipcontrolacr.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
         
      - name: Build and push Docker image
        run: |
            docker build -t wipcontrolacr.azurecr.io/wipcontrol-mysql:v1 -f mysql/Dockerfile2 .
            docker push wipcontrolacr.azurecr.io/wipcontrol-mysql:v1
 
      # - name: Build the frontend image and push it to ACR
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: wipcontrolacr.azurecr.io/wipcontrol-mysql:v1
      #     file: mysql/Dockerfile
      # - name: Azure login
      #   id: login
      #   uses: azure/login@v1.4.3
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: wipcontrol_rg 
          cluster-name: wipcontrolaks
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          manifests: |
             deploy-mysql.yaml
          images: 'wipcontrolacr.azurecr.io/${{ secrets.repository }}/wipcontrol-mysql:v1'
          pull-images: false