name: "Deploy Backend"
on:
  workflow_dispatch:
  push:
    paths:
      - "k8s-manifest/backend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      - name: ACR build
        id: build-push-acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant_id }}
          registry: ${{ secrets.registry }}
          repository: ${{ secrets.repository }}
          image:  wipcontrolacr.azurecr.io/wipcontrol-backend:v1
          folder: wipcontrol # wipcontrol/backend
          branch: master
          tag: ${{ github.sha }}
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: wipcontrol_rg 
          cluster-name: wipcontrolaks
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          manifests: |
             deploy-back.yaml
          images: '${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/wipcontrol:${{ github.sha }}'
          pull-images: false